### ISSUE TITLE
Upgrade to 1.0

### ISSUE THREAD

**Issue by jorgebucaran** [jamen/hyperapp-persist#10]
Just a friendly reminder that [Hyperapp 1.0](https://hackernoon.com/introducing-hyperapp-1-0-dbf4229abfef) has officially hit the streets and this module is now using an older API. Time to upgrade or deprecate! 👋 

See also: https://github.com/hyperapp/awesome/issues/18

**Comment by jamen** [comment]
I'll discontinue this package, and made something that uses actions, IndexedDB, and a better method than `unload`.  But lately I'm focused on non-JS projects so I dont know when I'll start.

**Comment by jorgebucaran** [comment]
Sounds good, thanks for contributing @jamen! I recently archived one of my older Node.js projects using GitHub's "archive" feature, you should give it a shot. 👋
